version: '3.3'
services:
    mongo:
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=macdo
            - MONGO_INITDB_ROOT_PASSWORD=macdo
        image: mongo
        volumes:
            - mongo-volume:/data/db
volumes:
  mongo-volume: