version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: toggle
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
